eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
server:
  port: 5000
spring:
  application:
    name: gateway-service
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9001

zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: user-service