eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
server:
  port: 9001
spring:
  application:
    name: zipkin-server
  rabbitmq:
    port: 5672
    username: static
    password: 123123
    host: localhost
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123123
    url: jdbc:mysql://localhost:3306/test
zipkin:
  storage:
    type: mysql